export interface LiquidVariable {
  label: string;
  code: string;
}

export interface LiquidVariableSection {
  title: string;
  description?: string;
  variables: LiquidVariable[];
}

export const liquidVariableSections: LiquidVariableSection[] = [
  {
    title: "Branding variables",
    description:
      "Variables related to the logo, logo width and accent color added from Templates → Customize branding page.",
    variables: [
      { label: "Logo", code: "{{ shop_logo_url }}" },
      { label: "Logo width", code: "{{ shop_logo_width }}" },
      { label: "Accent color", code: "{{ shop_accent_color }}" },
    ],
  },
  {
    title: "General variables",
    description:
      "General variables related to the order. These can be accessed either globally (name) or with the order prefix (order.name).",
    variables: [
      { label: "Shop name", code: "{{ shop_name }}" },
      { label: "Order number", code: "{{ order_number }}" },
      { label: "Order name (with # before number)", code: "{{ order_name }} or {{ name }}" },
      { label: "Order ID", code: "{{ id }}" },
      { label: "Purchase order number", code: "{{ po_number }}" },
      { label: "Date", code: "{{ date }} or {{ created_at }}" },
      { label: "Updated date", code: "{{ updated_at }}" },
      { label: "Processed date", code: "{{ processed_at }}" },
      { label: "Completed date (Draft orders)", code: "{{ completed_at }}" },
      { label: "Cancelled date", code: "{{ cancelled_at }}" },
      { label: "Closed / Archived date", code: "{{ closed_at }}" },
      { label: "Order Status page URL (online orders only)", code: "{{ order_status_url }}" },
      { label: "Location (POS orders only)", code: "{{ location }}" },
      { label: "Billing address", code: "{{ billing_address }}" },
      { label: "Shipping address", code: "{{ shipping_address }}" },
      { label: "Shipping methods (collection of shipping lines)", code: "{{ shipping_methods }} or {{ shipping_lines }}" },
      { label: "Shipping method", code: "{{ shipping_method.title }} or {{ shipping_line.title }}" },
      { label: "Pickup in Store (true/false)", code: '{% if pickup_in_store? %} ... {% endif %}' },
      { label: "Customer", code: "{{ customer }}" },
      { label: "Customer locale", code: "{{ customer_locale }}" },
      { label: "Email", code: "{{ email }}" },
      { label: "Financial status", code: "{{ financial_status }}" },
      { label: "Fulfillment status", code: "{{ fulfillment_status }}" },
      { label: "Fulfillment service", code: "{{ fulfillment_service }}" },
      { label: "Discounts amount (collection)", code: "{{ discounts_amount }}" },
      { label: "Discounts savings (collection)", code: "{{ discounts_savings }}" },
      { label: "Payment methods", code: "{{ payment_methods }}" },
      { label: "Payment method", code: "{{ payment_method }}" },
      { label: "Payment gateways", code: "{{ gateways }}" },
      { label: "Payment gateway", code: "{{ gateway }}" },
      { label: "Total items count", code: "{{ total_items }} or {{ item_count }}" },
      { label: "Total weight", code: "{{ total_weight }}" },
      { label: "Total weight with unit", code: "{{ total_weight | weight_with_unit }}" },
      { label: "Order Currency (currency code of order)", code: "{{ order_currency }} or {{ currency }}" },
      { label: "Subtotal price", code: "{{ subtotal_price | money }} or {{ current_subtotal_price | money }}" },
      { label: "Shipping price", code: "{{ shipping_price | money }}" },
      { label: "Total discounts", code: "{{ total_discounts | money }} or {{ current_total_discounts | money }}" },
      { label: "Total duties", code: "{{ total_duties | money }} or {{ duties_price | money }}" },
      { label: "Total tax", code: "{{ total_tax | money }} or {{ tax_price | money }} or {{ current_total_tax | money }}" },
      { label: "Total line items tax", code: "{{ total_line_items_tax | money }}" },
      { label: "Total shipping tax", code: "{{ total_shipping_tax | money }}" },
      { label: "Total price", code: "{{ total_price | money }} or {{ current_total_price | money }} or {{ total_net_amount }}" },
      { label: "Total paid", code: "{{ total_paid | money }}" },
      { label: "Total refunds", code: "{{ total_refunds | money }} or {{ total_refunded_amount }}" },
      { label: "Total Gift Cards", code: "{{ total_gift_cards | money }} or {{ gift_cards_price | money }}" },
      { label: "Transactions", code: "{{ transactions }}" },
      { label: "Order attributes", code: "{{ attributes }}" },
      { label: "Order note", code: "{{ note }}" },
      { label: "Order tags", code: "{% for tag in tags %} {{ tag }} {% endfor %}" },
    ],
  },
  {
    title: "Shop details",
    description: "Details about the shop where the order was placed.",
    variables: [
      { label: "Shop name", code: "{{ shop.name }}" },
      { label: "Shop email", code: "{{ shop.email }}" },
      { label: "Shop domain", code: "{{ shop.domain }}" },
      { label: "Shop owner", code: "{{ shop.owner }}" },
      { label: "Shop street address", code: "{{ shop.address1 }}" },
      { label: "Shop street address line 2", code: "{{ shop.address2 }}" },
      { label: "Shop city", code: "{{ shop.city }}" },
      { label: "Shop province", code: "{{ shop.province }}" },
      { label: "Shop province code", code: "{{ shop.province_code }}" },
      { label: "Shop postal code / ZIP code", code: "{{ shop.zip }}" },
      { label: "Shop country name", code: "{{ shop.country }}" },
      { label: "Shop country code", code: "{{ shop.country_code }}" },
      { label: "Shop phone number", code: "{{ shop.phone }}" },
      { label: "Shop taxes included in product prices", code: "{{ shop.taxes_included }}" },
    ],
  },
  {
    title: "Location details",
    description:
      "Location details of the shop where the order was created. POS orders include the POS location.",
    variables: [
      { label: "Location name", code: "{{ location.name }}" },
      { label: "Address 1", code: "{{ location.address1 }}" },
      { label: "Address 2", code: "{{ location.address2 }}" },
      { label: "City", code: "{{ location.city }}" },
      { label: "Province", code: "{{ location.province }}" },
      { label: "Province code", code: "{{ location.province_code }}" },
      { label: "Postal code / ZIP code", code: "{{ location.zip }}" },
      { label: "Country", code: "{{ location.country }}" },
      { label: "Country code", code: "{{ location.country_code }}" },
      { label: "Phone number", code: "{{ location.phone }}" },
    ],
  },
  {
    title: "Address details",
    description:
      "Address details for the order. Choose which address to use: shipping_address, billing_address, or customer.default_address.",
    variables: [
      { label: "First name", code: "{{ shipping_address.first_name }}" },
      { label: "Last name", code: "{{ shipping_address.last_name }}" },
      { label: "Name", code: "{{ shipping_address.name }}" },
      { label: "Company", code: "{{ shipping_address.company }}" },
      { label: "Address 1", code: "{{ shipping_address.address1 }}" },
      { label: "Address 2", code: "{{ shipping_address.address2 }}" },
      { label: "Street", code: "{{ shipping_address.street }}" },
      { label: "City, province and zip formatted", code: "{{ shipping_address.city_province_zip }}" },
      { label: "City", code: "{{ shipping_address.city }}" },
      { label: "Province", code: "{{ shipping_address.province }}" },
      { label: "Province code", code: "{{ shipping_address.province_code }}" },
      { label: "Postal code / ZIP code", code: "{{ shipping_address.zip }}" },
      { label: "Country", code: "{{ shipping_address.country }}" },
      { label: "Country code", code: "{{ shipping_address.country_code }}" },
      { label: "Phone number", code: "{{ shipping_address.phone }}" },
      {
        label: "Member of EU (true/false)",
        code: '{% if shipping_address.member_of_eu == true %}EU{% else %}Non-EU{% endif %}',
      },
    ],
  },
  {
    title: "Customer details",
    description: "Details about the customer associated with the order.",
    variables: [
      { label: "First name", code: "{{ customer.first_name }}" },
      { label: "Last name", code: "{{ customer.last_name }}" },
      { label: "Name", code: "{{ customer.name }}" },
      { label: "Email", code: "{{ customer.email }}" },
      { label: "Phone", code: "{{ customer.phone }}" },
      { label: "Default Address", code: "{{ customer.default_address }}" },
      { label: "Total spent", code: "{{ customer.total_spent | money }}" },
      { label: "Customer note", code: "{{ customer.note }}" },
      {
        label: "Tax exempt status (true/false)",
        code: '{% if customer.tax_exempt == true %}TAX EXEMPT{% endif %}',
      },
      { label: "Created date", code: "{{ customer.created_at }}" },
      { label: "Customer tags", code: "{% for tag in customer.tags %} ... {% endfor %}" },
    ],
  },
  {
    title: "Discount details",
    description: "Information about discounts applied to the order.",
    variables: [
      { label: "All Discounts", code: "{% for discount in discounts %} ... {% endfor %}" },
      { label: "Discounts with a Discount Code", code: "{% for discount in discount_codes %} ... {% endfor %}" },
      { label: "Code", code: "{{ discount.code }} or {{ discount.title }}" },
      { label: "Amount", code: "{{ discount.amount }}" },
      { label: "Savings", code: "{{ discount.savings }}" },
    ],
  },
  {
    title: "Discount applications",
    description: "Raw discount application objects applied to the order.",
    variables: [
      {
        label: "Discount Applications",
        code: "{% for discount_application in discount_applications %} ... {% endfor %}",
      },
    ],
  },
  {
    title: "Applied Discount details (Draft orders only)",
    description: "Applied discount information for Draft orders only.",
    variables: [
      { label: "Title", code: "{{ applied_discount.title }}" },
      { label: "Description", code: "{{ applied_discount.description }}" },
      { label: "Value Type (fixed or percentage)", code: "{{ applied_discount.value_type }}" },
      { label: "Value", code: "{{ applied_discount.value }}" },
      { label: "Amount", code: "{{ applied_discount.amount | money }}" },
    ],
  },
  {
    title: "Line item details",
    description: "Properties and pricing information for each line item.",
    variables: [
      { label: "Line items", code: "{% for line_item in line_items %} ... {% endfor %}" },
      { label: "Name", code: "{{ line_item.name }}" },
      { label: "Title", code: "{{ line_item.title }}" },
      { label: "Product title", code: "{{ line_item.product_title }}" },
      { label: "Quantity", code: "{{ line_item.quantity }}" },
      { label: "Fulfillable quantity", code: "{{ line_item.fulfillable_quantity }}" },
      { label: "Refunded quantity", code: "{{ line_item.refunded_quantity }}" },
      { label: "Price", code: "{{ line_item.price | money }}" },
      { label: "Original price", code: "{{ line_item.original_price | money }}" },
      { label: "Line price", code: "{{ line_item.line_price | money }}" },
      { label: "Total Discount", code: "{{ line_item.total_discount | money }}" },
      { label: "Discount per item (total_discount / quantity)", code: "{{ line_item.discount_per_item | money }}" },
      {
        label: "Discount Allocations",
        code: "{% for discount_allocation in line_item.discount_allocations %} {{ discount_allocation.amount | money }} {{ discount_allocation.discount_application_index }} {% endfor %}",
      },
      { label: "Total Tax", code: "{{ line_item.total_tax | money }}" },
      { label: "Total tax per item", code: "{{ total_tax_per_item | money }}" },
      {
        label: "Line Item Properties",
        code: "{% for property in line_item.properties %} {{ property.first }}: {{ property.last }} {% endfor %}",
      },
      { label: "Weight per item", code: "{{ line_item.weight }} or {{ line_item.grams }}" },
      { label: "Weight per item with unit", code: "{{ line_item.weight | weight_with_unit }}" },
      { label: "Total weight (item × qty)", code: "{{ line_item.total_weight }}" },
      { label: "Total weight with unit (item × qty)", code: "{{ line_item.total_weight | weight_with_unit }}" },
      { label: "SKU", code: "{{ line_item.sku }}" },
      { label: "Vendor", code: "{{ line_item.vendor }}" },
      { label: "HS Tariff Code", code: "{{ line_item.hs_tariff_code }}" },
      { label: "Country of Origin", code: "{{ line_item.country_of_origin }}" },
      { label: "Cost", code: "{{ line_item.cost | money }}" },
      { label: "Fulfillment", code: "{{ line_item.fulfillment }}" },
      { label: "Product", code: "{{ line_item.product }}" },
      { label: "Variant", code: "{{ line_item.variant }}" },
      { label: "Image", code: "{{ line_item.image | img_url: 'thumb' | img_tag }}" },
    ],
  },
  {
    title: "Payment terms",
    description: "Payment terms data and schedules.",
    variables: [
      { label: "Amount", code: "{{ payment_terms.amount | money }}" },
      { label: "Currency", code: "{{ payment_terms.currency }}" },
      { label: "Overdue", code: '{% if payment_terms.overdue %}Overdue{% endif %}' },
      { label: "Payment Terms Type", code: "{{ payment_terms.payment_terms_type }}" },
      { label: "Due in Days", code: "{{ payment_terms.due_in_days }}" },
      { label: "Payment Schedules", code: "{% for payment_schedule in payment_terms.payment_schedules %} ... {% endfor %}" },
      { label: "Current Payment Schedule", code: "{{ payment_terms.current_payment_schedule }}" },
      { label: "Current / Amount", code: "{{ payment_terms.current_payment_schedule.amount | money }}" },
      { label: "Current / Currency", code: "{{ payment_terms.current_payment_schedule.currency }}" },
      { label: "Current / Expected Payment Method", code: "{{ payment_terms.current_payment_schedule.expected_payment_method }}" },
      { label: 'Current / Issued At', code: '{{ payment_terms.current_payment_schedule.issued_at | date: "%b %e, %Y" }}' },
      { label: 'Current / Due At', code: '{{ payment_terms.current_payment_schedule.due_at | date: "%b %e, %Y" }}' },
      { label: 'Current / Completed At', code: '{{ payment_terms.current_payment_schedule.completed_at | date: "%b %e, %Y" }}' },
    ],
  },
  {
    title: "Refund details",
    description: "Details about refunds, refund line items, and adjustments.",
    variables: [
      { label: "Latest refund", code: "{{ latest_refund }}" },
      { label: "Refunds", code: "{% for refund in refunds %} ... {% endfor %}" },
      { label: "Date", code: "{{ refund.date }} or {{ refund.created_at }}" },
      { label: "Refund note", code: "{{ refund.note }}" },
      { label: "Restock", code: "{{ refund.restock }}" },
      { label: "Refund payment method", code: "{{ refund.payment_method }}" },
      { label: "Refund subtotal", code: "{{ refund.subtotal | money }}" },
      { label: "Refund total tax", code: "{{ refund.total_tax | money }}" },
      { label: "Refund total", code: "{{ refund.total | money }}" },
      { label: "Refund transactions", code: "{% for refund_transaction in refund.transactions %} ... {% endfor %}" },
      { label: "Refund order adjustments", code: "{% for order_adjustment in refund.order_adjustments %}{% endfor %}" },
      { label: "Order adjustment kind", code: "{{ order_adjustment.kind }}" },
      { label: "Order adjustment reason", code: "{{ order_adjustment.reason }}" },
      { label: "Order adjustment amount", code: "{{ order_adjustment.amount | money }}" },
      { label: "Order adjustment total tax", code: "{{ order_adjustment.total_tax | money }}" },
      { label: "Refund line items", code: "{% for refund_line_item in refund.refund_line_items %} ... {% endfor %}" },
      { label: "Refund line item quantity", code: "{{ refund_line_item.quantity }}" },
      { label: "Refund line item subtotal", code: "{{ refund_line_item.subtotal | money }}" },
      { label: "Refund line item total tax", code: "{{ refund_line_item.total_tax | money }}" },
      { label: "Refund line item", code: "{{ refund_line_item.line_item }}" },
    ],
  },
  {
    title: "Payment details",
    description: "Payment method details captured with the order.",
    variables: [
      { label: "Credit card number", code: "{{ payment_details.credit_card_number }}" },
      { label: "Credit card company", code: "{{ payment_details.credit_card_company }}" },
    ],
  },
  {
    title: "Transaction details",
    description: "Transaction records for payments and refunds.",
    variables: [
      { label: "Transactions", code: "{% for transaction in transactions %} ... {% endfor %}" },
      { label: "Payment transactions", code: "{% for transaction in payment_transactions %} ... {% endfor %}" },
      { label: "Refund transactions", code: "{% for transaction in refund_transactions %} ... {% endfor %}" },
      { label: "Amount", code: "{{ transaction.amount | money }}" },
      { label: "Authorization", code: "{{ transaction.authorization }}" },
      { label: "Date", code: "{{ transaction.date }} or {{ transaction.created_at }}" },
      { label: "Gateway", code: "{{ transaction.gateway }}" },
      { label: "Payment method (derived from gateway)", code: "{{ transaction.gateway | payment_method }}" },
      { label: "Kind", code: "{{ transaction.kind }}" },
      { label: "Message", code: "{{ transaction.message }}" },
      { label: "Status", code: "{{ transaction.status }}" },
    ],
  },
  {
    title: "Shipping line details",
    description: "Chosen shipping rate information.",
    variables: [
      { label: "Shipping lines", code: "{% for shipping_line in shipping_lines %} ... {% endfor %}" },
      { label: "Title", code: "{{ shipping_line.title }}" },
      { label: "Code", code: "{{ shipping_line.code }}" },
      { label: "Price", code: "{{ shipping_line.price | money }}" },
    ],
  },
  {
    title: "Tax line details",
    description: "Tax lines calculated for the order.",
    variables: [
      { label: "Tax lines", code: "{% for tax_line in tax_lines %} ... {% endfor %}" },
      { label: "Title", code: "{{ tax_line.title }}" },
      { label: "Rate", code: "{{ tax_line.rate }}" },
      { label: "Price", code: "{{ tax_line.price | money }}" },
    ],
  },
  {
    title: "Fulfillment details",
    description: "Shipment and tracking information.",
    variables: [
      { label: "Latest fulfillment", code: "{{ latest_fulfillment }}" },
      { label: "Fulfillments", code: "{% for fulfillment in fulfillments %} ... {% endfor %}" },
      { label: "Date", code: "{{ fulfillment.date }} or {{ fulfillment.created_at }}" },
      { label: "Tracking number", code: "{{ fulfillment.tracking_number }}" },
      { label: "Tracking company", code: "{{ fulfillment.tracking_company }}" },
    ],
  },
  {
    title: "Product details",
    description: "Product object fields.",
    variables: [
      { label: "Products", code: "{% for product in products %} ... {% endfor %}" },
      { label: "Title", code: "{{ product.title }}" },
      { label: "Content", code: "{{ product.content }}" },
      { label: "Description", code: "{{ product.description }}" },
      { label: "Handle", code: "{{ product.handle }}" },
      { label: "Option names", code: "{{ product.options }}" },
      { label: "Tags", code: "{{ product.tags }}" },
      { label: "Type", code: "{{ product.type }}" },
      { label: "Vendor", code: "{{ product.vendor }}" },
      { label: "URL", code: "{{ product.url }}" },
      { label: "Featured image (first image)", code: "{{ product.featured_image | img_url: 'large' | img_tag }}" },
      { label: "Images", code: "{{ product.images }}" },
      { label: "Variants", code: "{{ product.variants }}" },
    ],
  },
  {
    title: "Variant details",
    description: "Variant object fields.",
    variables: [
      { label: "Variants", code: "{% for variant in variants %} ... {% endfor %}" },
      { label: "Title", code: "{{ variant.title }}" },
      { label: "Price", code: "{{ variant.price | money }}" },
      { label: "Compare at price", code: "{{ variant.compare_at_price | money }}" },
      { label: "Weight", code: "{{ variant.weight }} or {{ variant.grams }}" },
      { label: "Weight with unit", code: "{{ variant.weight | weight_with_unit }}" },
      { label: "Inventory quantity", code: "{{ variant.inventory_quantity }}" },
      { label: "SKU", code: "{{ variant.sku }}" },
      { label: "Barcode", code: "{{ variant.barcode }}" },
      { label: "Option 1", code: "{{ variant.option1 }}" },
      { label: "Option 2", code: "{{ variant.option2 }}" },
      { label: "Option 3", code: "{{ variant.option3 }}" },
      { label: "Image", code: "{{ variant.image | img_url: 'thumb' | img_tag }}" },
    ],
  },
  {
    title: "Liquid filters",
    description: "Available liquid filters.",
    variables: [
      { label: "Image tag", code: "{{ 'example.png' | img_tag }}" },
      { label: "Money format", code: "{{ product.price | money }}" },
      { label: "Money format with currency", code: "{{ product.price | money_with_currency }}" },
      { label: "Money format without currency", code: "{{ product.price | money_without_currency }}" },
      { label: "Money format without decimals", code: "{{ product.price | money_no_decimals }}" },
    ],
  },
];
